In [1]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [5]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print(a)
print('--------------')
#a.shape
## flatten the array
print(a.ravel())
print('--------------')
a.shape = (6, 2)
print(a) 
print('--------------')
print(a.T)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)   # -1 根据数据自动计算要生成多少列

[[ 9.  6.  5.  6.]
 [ 0.  6.  1.  5.]
 [ 7.  5.  5.  6.]]
--------------
[ 9.  6.  5.  6.  0.  6.  1.  5.  7.  5.  5.  6.]
--------------
[[ 9.  6.]
 [ 5.  6.]
 [ 0.  6.]
 [ 1.  5.]
 [ 7.  5.]
 [ 5.  6.]]
--------------
[[ 9.  5.  0.  1.  7.  5.]
 [ 6.  6.  6.  5.  5.  6.]]


In [32]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print a
print '---'
print b
print '---'
print np.hstack((a,b))
#np.vstack((a,b))

[[ 5.  6.]
 [ 1.  5.]]
---
[[ 8.  6.]
 [ 9.  0.]]
---
[[ 5.  6.  8.  6.]
 [ 1.  5.  9.  0.]]


In [6]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print('------')
print(np.hsplit(a,3))
print('------')
print(np.hsplit(a,(3,4)))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print('------')
print(a)
np.vsplit(a,3)

[[ 9.  1.  7.  9.  0.  4.  3.  6.  9.  6.  2.  7.]
 [ 1.  7.  9.  7.  0.  4.  9.  1.  1.  8.  6.  5.]]
------
[array([[ 9.,  1.,  7.,  9.],
       [ 1.,  7.,  9.,  7.]]), array([[ 0.,  4.,  3.,  6.],
       [ 0.,  4.,  9.,  1.]]), array([[ 9.,  6.,  2.,  7.],
       [ 1.,  8.,  6.,  5.]])]
------
[array([[ 9.,  1.,  7.],
       [ 1.,  7.,  9.]]), array([[ 9.],
       [ 7.]]), array([[ 0.,  4.,  3.,  6.,  9.,  6.,  2.,  7.],
       [ 0.,  4.,  9.,  1.,  1.,  8.,  6.,  5.]])]
------
[[ 9.  2.]
 [ 6.  9.]
 [ 5.  0.]
 [ 5.  6.]
 [ 7.  2.]
 [ 4.  6.]
 [ 9.  0.]
 [ 7.  4.]
 [ 3.  1.]
 [ 3.  8.]
 [ 0.  3.]
 [ 4.  9.]]


[array([[ 9.,  2.],
        [ 6.,  9.],
        [ 5.,  0.],
        [ 5.,  6.]]), array([[ 7.,  2.],
        [ 4.,  6.],
        [ 9.,  0.],
        [ 7.,  4.]]), array([[ 3.,  1.],
        [ 3.,  8.],
        [ 0.,  3.],
        [ 4.,  9.]])]

In [8]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
140034330576656
140034330576656


In [9]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print(c is a)
print('-------')
c.shape = 2,6
print(a.shape)
print('-------')
c[0,4] = 1234
print(a)
print('-------')
print(id(a))
print(id(c))

False
-------
(3, 4)
-------
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
-------
140034330576656
140034330614560


In [10]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
print(d is a)
d[0,0] = 9999
print(d) 
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
